name = "construct-app-registry"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "app-registry"
database_id = "885d0e16-61f6-4431-aec2-f82678148270"
